"Mission Credits" hintC [
"The author of this mission would like to thank the following people for their contributions to Resistance:",
"TCB Psycho - A3 Wounding System (TCB Revive)",
"Giallustio - Logistics",
"aerson - Player Markers & Loadout Scripts",
"BangaBob - Enemy Occupation System (EOS)",
"SpunFIN - AI Spawn Script Pack",
"Shuko - Taskmaster Script & SHK Pos",
"Task Force Blackjack - Headless Client Solution",
"zuff - Group Management",
"Ollem - TPWC AI Suppression System",
"Conroy - Cleanup Module",
"Wolfenswan [FA] - Civilian Assassins script",
"MadT - MAD Ambient Life scripts",
"otstrel.ru - Significant Assistance during Mission development",
"Zorrobyte - Modified dynamic EOS scripts",
"Kylania - Various scripts",
"This server, for running the mission",
"You, for playing!"
];