"Welcome to resistance" hintC [
"Supplies are low use them wisely.",
"Your mission is to clear out the surrounding towns and scavenge arms and equipment for the resistance.",
"All you have is what you start with only the starter vehicles respawn when destroyed.",
"Teleport is available at the flag.",
"Excess Gear can be stored at the storage Terminals (looks like ATM's at base)",
"Check the 'Mission Brief' for more information.",
"For performance Dynamic simulation is on ranging from 1.5k to 3k, damage is done but it will not take affect untill activation.",
"",
"Please follow the server rules:",
"1: No Teamkilling",
"2: Respect Each other",
"Failing to abide by the above will result in your immediate removal from the server.",
"Note: We advise you to join our Teamspeak as communication is the key to successfully completing the missions. (ts3: ts3.iron-fists.eu OR 81.19.212.66)",
"Website: www.iron-fists.eu",
"PLAY FAIR AND WITH HONOUR",
"TASK FORCE RADIOS is used but NOT REQUIRED"];
