if (!isServer) exitWith {};
_location = getmarkerpos (_this select 0);
_Tent = "Land_TentDome_F" createvehicle _location;
_Tent allowdamage false;
_Tent setVariable ["R3F_LOG_disabled", true,true];
_box = "IG_supplyCrate_F" createvehicle [(_location select 0),(_location select 1) + 3,0];
_box allowdamage false;
_box setVariable ["R3F_LOG_disabled", true,true];
_fire = "Campfire_burning_F" createvehicle [(_location select 0),(_location select 1)-3,0];
_fire allowdamage false;
_fire setVariable ["R3F_LOG_disabled", true,true];
clearweaponcargoGlobal _box;
clearmagazinecargoGlobal _box;
clearitemcargoGlobal _box;
clearBackpackCargoGlobal _box;
[[_Tent,["Teleport","Client\teleport.sqf"]],"addAction",true,true] call BIS_fnc_MP;
_Marker = createMarker [format["respawn_west_%1",(_this select 0)], _location];
_Marker setMarkerColor "ColorBLUFOR";
_Marker setMarkerType  "b_installation";
