[[
  ["Taskcity1","Capture Kavala","The western city of Kavala is an important objective in the liberation of Altis, it's capture is a high priority.",true,["mrk_obj_1",getmarkerpos "city_1","o_installation","ColorRed","Capture Kavala"],"assigned"],
  ["Taskcity2","Capture Athira","The central city of Athira is an important objective in the liberation of Altis, it's capture is a high priority.",true,["mrk_obj_2",getmarkerpos "city_2","o_installation","ColorRed","Capture Athira"]],
  ["Taskcity3","Capture Pyrgos","The eastern city of Pyrgos is an important objective in the liberation of Altis, it's capture is a high priority.",true,["mrk_obj_3",getmarkerpos "city_3","o_installation","ColorRed","Capture Pyrgos"]],
  
  ["Taskairfield1","Capture Molos Airfield","There are six airfields scattered around the island, these are critical for the continued flow of supplies for CSAT occupation forces. Capturing these will be vital to our sucess.",true,["airobj_1_1",getmarkerpos "airfield_1_1","n_plane","ColorRed","Capture Molos Airfield"]],
  ["Taskairfield2","Capture Almyra airfield","There are six airfields scattered around the island, these are critical for the continued flow of supplies for CSAT occupation forces. Capturing these will be vital to our sucess.",true,["airobj_1_2",getmarkerpos "airfield_1_2","n_plane","ColorRed","Capture Almyra airfield"]],
  ["Taskairfield3","Capture Airbase airfield","There are six airfields scattered around the island, these are critical for the continued flow of supplies for CSAT occupation forces. Capturing these will be vital to our sucess.",true,["airobj_1_3",getmarkerpos "airfield_1_3","n_plane","ColorRed","Capture Airbase airfield"]],
  ["Taskairfield4","Capture Southeast airfield","There are six airfields scattered around the island, these are critical for the continued flow of supplies for CSAT occupation forces. Capturing these will be vital to our sucess.",true,["airobj_1_4",getmarkerpos "airfield_1_4","n_plane","ColorRed","Capture Southeast airfield"]],
  ["Taskairfield5","Capture Northwest airfield","There are six airfields scattered around the island, these are critical for the continued flow of supplies for CSAT occupation forces. Capturing these will be vital to our sucess.",true,["airobj_1_5",getmarkerpos "airfield_1_5","n_plane","ColorRed","Capture Northwest airfield"]],
  ["Taskairfield6","Capture AAC airfield","There are six airfields scattered around the island, these are critical for the continued flow of supplies for CSAT occupation forces. Capturing these will be vital to our sucess.",true,["airobj_1_6",getmarkerpos "airfield_1_6","n_plane","ColorRed","Capture AAC airfield"]],
  
  ["sectasktower1","Secondary: Capture Kavala Tower","Near each city is a transmitter tower responsible for directing patrols for the region. Capturing them is not required but highly recommended to make cities easier to capture.",true,["towerobj_1",getmarkerpos "tower_1","loc_Transmitter","ColorYellow","Capture Kavala Tower"]],
  ["sectasktower2","Secondary: Capture Athira Tower","Near each city is a transmitter tower responsible for directing patrols for the region. Capturing them is not required but highly recommended to make cities easier to capture.",true,["towerobj_2",getmarkerpos "tower_2","loc_Transmitter","ColorYellow","Capture Athira Tower"]],
  ["sectasktower3","Secondary: Capture Pyrgos Tower","Near each city is a transmitter tower responsible for directing patrols for the region. Capturing them is not required but highly recommended to make cities easier to capture.",true,["towerobj_3",getmarkerpos "tower_3","loc_Transmitter","ColorYellow","Capture Pyrgos Tower"]]  
  ],[
  ["Situation","The CSAT Alliance has invaded the Republic of Altis and currently has complete control of it. The NATO Counter invasion was a complete failure and the FIA has been left to fend for itself. Now these rebels must strike back to liberate their homeland."],
  ["Synopsis","This mission is designed to be played online. Liberate the island by capturing villages and towns to build up your arsenal in order to capture the three main cities and six airfields of Altis. Capture old AAF bases to access more advanced weaponry."],
  ["Credits","Credits can be viewed at the Main base on the 'mission credits' sign."]
]] call compile preprocessfilelinenumbers "core\scripts\shk_taskmaster.sqf";